version: "2"
services:
  go:
    image: golang:1.13
    volumes:
      - ./:/code
    entrypoint:
      - sleep
      - "86400"
    working_dir: /code

#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#      - 15672:15672
#      - 5672:5672

  beanstalkd:
    image: schickling/beanstalkd
    ports:
      - 11300:11300

  beanstalkd-console:
    image: schickling/beanstalkd-console
    ports:
      - 2080:2080
    environment:
      BEANSTALK_SERVERS: "beanstalkd:11300"